name: Continuous Integration

on:
  push:
    # branches: [master] #TODO(achrinza): Temporarily commented out for testing.
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [master]
  schedule:
    - cron: '0 2 * * 1' # At 02:00 on Monday

env:
  NODE_OPTIONS: --max-old-space-size=4096

jobs:
  test:
    name: Test
    timeout-minutes: 15
    env:
      COUCHDB_URL: http://admin:pass@127.0.0.1
    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: [8.9, 10, 12, 14, 16]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    services:
      couchdb:
        image: couchdb
        env:
          COUCHDB_USER: admin
          COUCHDB_PASSWORD: pass
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Bootstrap project
      #   if: ${{ matrix.node-version != '8.9' }}
      #   run: npm ci --ignore-scripts
      # - name: Bootstrap project (Node v8.9)
        if: ${{ matrix.node-version == '8.9' }}
        run: npm install --ignore-scripts
      - name: Run tests
        run: npm test --ignore-scripts

  code-lint:
    name: Code Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14
        uses: actions/setup-node@v2
        with:
          node-version: 14
      - name: Bootstrap project
      #   if: ${{ matrix.node-version != '8.9' }}
      #   run: npm ci --ignore-scripts
      # - name: Bootstrap project (Node v8.9)
        if: ${{ matrix.node-version == '8.9' }}
        run: npm install --ignore-scripts
      - name: Verify code linting
        run: npm run lint

  commit-lint:
    name: Commit Lint
    runs-on: ubuntu-latest
    if: ${{ github.event.pull_request }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Use Node.js 14
        uses: actions/setup-node@v2
        with:
          node-version: 14
      - name: Bootstrap project
      #   if: ${{matrix.node-version != '8.9'}}
      #   run: npm ci --ignore-scripts
      # - name: Bootstrap project (Node v8.9)
        if: ${{matrix.node-version == '8.9'}}
        run: npm install --ignore-scripts
      - name: Verify commit linting
        run: npx commitlint --from origin/master --to HEAD --verbose
